name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna exec npm run test
      - run: npx lerna exec npm run build
      - run: npx lerna exec npm pack
      - run: npx lerna exec npm run docs
      - run: |
          VERSION_BUMP=$(node scripts/conventional-recommended-bump.js)
          npx lerna version --conventional-commits --changelog-preset conventionalcommits --create-release=github --yes $VERSION_BUMP
          npx lerna publish --yes from-package
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     access: public
      #     check-version: false
