name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna exec npm run test
      - run: npx lerna exec npm run build
      - run: npx lerna exec npm pack
      # - run: npx lerna exec npm run docs
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          VERSION_BUMP=$(node scripts/conventional-recommended-bump.js)
          npx lerna publish $VERSION_BUMP --include-merged-tags --no-verify-access --conventional-commits --changelog-preset conventionalcommits --create-release=github --yes
